import LayoutJustHeader from "../components/layout/LayoutJustHeader";
import MainLayout from "../components/layout/MainLayout";

const routes = [
  {
    path: "/dashboard",
    component: "Dashboard",
    exact: true,
    title: "Trình điều khiển",
    isPrivate: false,
    layout: MainLayout,
  }, {
    path: "/login",
    component: "LoginPage",
    exact: true,
    title: "Đăng nhập",
    isPrivate: false,
  },
  {
    path: "/auth/callback",
    component: "AuthCallback",
    exact: true,
    title: "Xử lý đăng nhập",
    isPrivate: false,
  },
  {
    path: "/profile",
    component: "ProfilePage",
    exact: true,
    title: "Hồ sơ cá nhân",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/student",
    component: "StudentDashboard",
    exact: true,
    title: "Hồ sơ cá nhân",
    isPrivate: false,
    layout: LayoutJustHeader,
  },
  {

    path: "/courses",
    component: "Course",
    exact: true,
    title: "Quản lý Khóa học",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/slottime",
    component: "Slot_time",
    exact: true,
    title: "Quản lý Khung giờ",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/room",
    component: "Room",
    exact: true,
    title: "Quản lý Phòng học",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/class",
    component: "Class",
    exact: true,
    title: "Quản lý Lớp học",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/classsection",
    component: "ClassSection",
    exact: true,
    title: "Quản lý Lớp học phần",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/lecturers",
    component: "Lecturer",
    exact: true,
    title: "Quản lý Giảng viên",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/students",
    component: "Student",
    exact: true,
    title: "Quản lý Học viên",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/subjects",
    component: "Subject",
    exact: true,
    title: "Quản lý Học phần",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "/programs",
    component: "Program",
    exact: true,
    title: "Quản lý Chương trình đào tạo",
    isPrivate: false,
    layout: MainLayout,
  },
  {
    path: "student/results",
    component: "StudentLearningResults",
    exact: true,
    title: "Kết quả học tập",
    isPrivate: false,
    layout: LayoutJustHeader,
  },
  {
    path: "student/schedules",
    component: "StudentSchedules",
    exact: true,
    title: "Kết quả học tập",
    isPrivate: false,
    layout: LayoutJustHeader,
  },
];

export default routes;